"""remove victim system model

Revision ID: 636dd064cec7
Revises: 6a1b2c3d4e5f
Create Date: 2026-06-01 02:01:53.617045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "636dd064cec7"
down_revision: Union[str, Sequence[str], None] = "6a1b2c3d4e5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_victim_systems_idx"), table_name="victim_systems")
    op.drop_table("victim_systems")
    op.drop_column("response_plan_actions", "error_message")
    op.drop_column("response_plan_actions", "executed_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "response_plan_actions",
        sa.Column(
            "executed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "response_plan_actions",
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "victim_systems",
        sa.Column("idx", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "ip_address", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("port", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "mcp_status", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("idx", name=op.f("victim_systems_pkey")),
    )
    op.create_index(
        op.f("ix_victim_systems_idx"), "victim_systems", ["idx"], unique=False
    )
    # ### end Alembic commands ###
